local colors = {
  bg = "#1D1F21",
  fg = "#969896",
  caret = "#AEAFAD",
  invisibles = "#4B4E55",
  lineHighlight = "#282A2E",
  selection = "#373B41",
  comment = "#6a6a6a",
  purple = "#B294BB",
  blue = "#7587a6",
  red = "#cf7777",
  green = "#8f9d6a",
  invalid_bg = "#DF5F5F",
  invalid_fg = "#CED2CF",
  separator_bg = "#82A3BF",
  deprecated_bg = "#B798BF",
  support_bg = "#282829",
}

local highlights = {
  Normal = { fg = colors.fg, bg = colors.bg },
  NormalFloat = { fg = colors.fg, bg = colors.bg },
  NormalNC = { fg = colors.fg, bg = colors.bg },
  Comment = { fg = colors.comment, italic = true },
  Constant = { fg = colors.purple },
  String = { fg = colors.red },
  Character = { fg = colors.purple },
  Number = { fg = colors.purple },
  Boolean = { fg = colors.purple },
  Float = { fg = colors.purple },
  Identifier = { fg = colors.blue },
  Function = { fg = colors.green },
  Statement = { fg = colors.purple },
  Conditional = { fg = colors.purple },
  Repeat = { fg = colors.purple },
  Label = { fg = colors.purple },
  Operator = { fg = colors.fg },
  Keyword = { fg = colors.purple },
  Exception = { fg = colors.purple },
  PreProc = { fg = colors.purple },
  Type = { fg = colors.blue },
  StorageClass = { fg = colors.purple },
  Structure = { fg = colors.purple },
  Typedef = { fg = colors.purple },
  Property = { fg = colors.blue },
  Field = { fg = colors.blue },
  Parameter = { fg = colors.purple },
  Variable = { fg = colors.blue },
  Namespace = { fg = colors.blue },
  Package = { fg = colors.blue },
  Class = { fg = colors.blue },
  Interface = { fg = colors.blue },
  Enum = { fg = colors.blue },
  EnumMember = { fg = colors.purple },
  Struct = { fg = colors.blue },
  Union = { fg = colors.blue },
  Event = { fg = colors.blue },
  Func = { fg = colors.green },
  Method = { fg = colors.green },
  Member = { fg = colors.green },
  Macro = { fg = colors.purple },
  PreCondit = { fg = colors.purple },
  Include = { fg = colors.purple },
  Define = { fg = colors.purple },
  Cursor = { fg = colors.caret },
  Special = { fg = colors.caret },
  SpecialChar = { fg = colors.caret },
  Tag = { fg = colors.blue },
  Delimiter = { fg = colors.fg },
  SpecialComment = { fg = colors.comment },
  Debug = { fg = colors.caret },
  Underlined = { underline = true },
  Bold = { bold = true },
  Italic = { italic = true },
  Error = { fg = colors.invalid_fg, bg = colors.invalid_bg },
  Todo = { fg = colors.bg, bg = colors.purple },
  qfLineNr = { fg = colors.blue },
  qfFileName = { fg = colors.blue },
  htmlTag = { fg = colors.blue },
  htmlEndTag = { fg = colors.blue },
  htmlTagName = { fg = colors.blue },
  htmlArg = { fg = colors.purple },
  htmlComment = { fg = colors.comment },
  htmlSpecialTagName = { fg = colors.blue },
  rubyInterpolationDelimiter = { fg = colors.caret },
  erbDelimiter = { fg = colors.caret },
  erbInterp = { fg = colors.purple },
  htmlCss = { fg = colors.green },
  cssSelectorOp = { fg = colors.purple },
  cssSelectorPseudo = { fg = colors.purple },
  cssSelectorTag = { fg = colors.blue },
  cssSelectorClass = { fg = colors.blue },
  cssSelectorId = { fg = colors.green },
  cssSelectorAttr = { fg = colors.purple },
  cssProp = { fg = colors.blue },
  cssUnit = { fg = colors.purple },
  jsonKeyword = { fg = colors.blue },
  jsonString = { fg = colors.red },
  jsonNumber = { fg = colors.purple },
  jsonBoolean = { fg = colors.purple },
  jsonNull = { fg = colors.purple },
  jsonComment = { fg = colors.comment },
  luaIn = { fg = colors.purple },
  luaFunction = { fg = colors.green },
  luaTable = { fg = colors.fg },
  luaOperator = { fg = colors.fg },
  pythonOperator = { fg = colors.purple },
  pythonEscape = { fg = colors.purple },
  rubySymbol = { fg = colors.purple },
  rubyInterpolation = { fg = colors.caret },
  rustQuestionMark = { fg = colors.purple },
  rustSelf = { fg = colors.purple },
  rustType = { fg = colors.blue },
  rustFunc = { fg = colors.green },
  rustModPath = { fg = colors.blue },
  javascriptVariable = { fg = colors.blue },
  javascriptIdentifier = { fg = colors.purple },
  javascriptNull = { fg = colors.purple },
  javascriptBoolean = { fg = colors.purple },
  javascriptNumber = { fg = colors.purple },
  javascriptString = { fg = colors.red },
  javascriptTemplateStrings = { fg = colors.red },
  javascriptTemplateString = { fg = colors.red },
  javascriptRegex = { fg = colors.red },
  javascriptException = { fg = colors.purple },
  typescriptReserved = { fg = colors.purple },
  typescriptIdentifier = { fg = colors.blue },
  typescriptNull = { fg = colors.purple },
  typescriptBoolean = { fg = colors.purple },
  typescriptNumber = { fg = colors.purple },
  typescriptString = { fg = colors.red },
  typescriptTemplateString = { fg = colors.red },
  typescriptArray = { fg = colors.fg },
  typescriptUnion = { fg = colors.purple },
  typescriptParens = { fg = colors.fg },
  typescriptInterface = { fg = colors.blue },
  typescriptType = { fg = colors.purple },
  typescriptClass = { fg = colors.blue },
  typescriptFunc = { fg = colors.green },
  tsxTag = { fg = colors.blue },
  tsxComponent = { fg = colors.green },
  tsxIdentifier = { fg = colors.green },
  vimCommand = { fg = colors.purple },
  vimVar = { fg = colors.blue },
  vimFunc = { fg = colors.green },
  LineNr = { fg = colors.invisibles },
  CursorLineNr = { fg = colors.fg },
  CursorLine = { bg = colors.lineHighlight },
  CursorColumn = { bg = colors.lineHighlight },
  Visual = { bg = colors.selection },
  VisualNOS = { bg = colors.selection },
  Search = { fg = colors.bg, bg = colors.blue },
  IncSearch = { fg = colors.bg, bg = colors.green },
  Substitute = { fg = colors.bg, bg = colors.green },
  MatchParen = { bg = colors.selection },
  NonText = { fg = colors.invisibles },
  Whitespace = { fg = colors.invisibles },
  Folded = { fg = colors.comment },
  FoldColumn = { fg = colors.invisibles },
  SignColumn = { fg = colors.fg },
  SignColumnSB = { fg = colors.fg },
  ErrorMsg = { fg = colors.invalid_fg, bg = colors.invalid_bg },
  WarningMsg = { fg = colors.deprecated_bg },
  ModeMsg = { fg = colors.fg },
  MoreMsg = { fg = colors.fg },
  Question = { fg = colors.green },
  Directory = { fg = colors.blue, bold = true },
  Title = { fg = colors.red, bold = true },
  Separator = { fg = colors.separator_bg },
  SpecialKey = { fg = colors.invisibles },
  Pmenu = { fg = colors.fg, bg = colors.bg },
  PmenuSel = { bg = colors.selection },
  PmenuSbar = { bg = colors.lineHighlight },
  PmenuThumb = { bg = colors.selection },
  TabLine = { fg = colors.fg },
  TabLineSel = { fg = colors.green },
  TabLineFill = { bg = colors.bg },
  StatusLine = { fg = colors.fg, bg = colors.lineHighlight },
  StatusLineNC = { fg = colors.comment },
  WinBar = { fg = colors.fg, bg = colors.bg },
  WinBarNC = { fg = colors.comment, bg = colors.bg },
  VertSplit = { fg = colors.selection },
  ColorColumn = { bg = colors.lineHighlight },
  QuickFixLine = { fg = colors.green },
  ToolbarLine = { fg = colors.fg },
  ToolbarButton = { fg = colors.fg, bold = true },
  External = { fg = colors.fg },
  Breakpoint = { fg = colors.invalid_fg, bg = colors.invalid_bg },
  SigBreakpoint = { fg = colors.invalid_fg, bg = colors.invalid_bg },
  NetrwDir = { fg = colors.blue },
  NetrwFile = { fg = colors.fg },
  NetrwLink = { fg = colors.green },
  NetrwLinkTarget = { fg = colors.green },
  DiagnosticError = { fg = colors.invalid_bg },
  DiagnosticWarn = { fg = colors.deprecated_bg },
  DiagnosticInfo = { fg = colors.blue },
  DiagnosticHint = { fg = colors.green },
  DiagnosticUnderlineError = { undercurl = true, sp = colors.invalid_bg },
  DiagnosticUnderlineWarn = { undercurl = true, sp = colors.deprecated_bg },
  DiagnosticUnderlineInfo = { undercurl = true, sp = colors.blue },
  DiagnosticUnderlineHint = { undercurl = true, sp = colors.green },
  LspReferenceRead = { bg = colors.selection },
  LspReferenceWrite = { bg = colors.selection },
  LspReferenceText = { bg = colors.selection },
  LspSignatureActiveParameter = { bg = colors.lineHighlight },
  LspCodeLens = { fg = colors.comment },
  LspCodeLensSeparator = { fg = colors.comment },
  ["@type"] = { fg = colors.blue },
  ["@type.builtin"] = { fg = colors.blue },
  ["@type.definition"] = { fg = colors.blue },
  ["@variable"] = { fg = colors.blue },
  ["@variable.builtin"] = { fg = colors.purple },
  ["@constant"] = { fg = colors.purple },
  ["@constant.builtin"] = { fg = colors.purple },
  ["@string"] = { fg = colors.red },
  ["@string.escape"] = { fg = colors.purple },
  ["@string.regex"] = { fg = colors.red },
  ["@comment"] = { fg = colors.comment, italic = true },
  ["@keyword"] = { fg = colors.purple },
  ["@keyword.function"] = { fg = colors.purple },
  ["@keyword.operator"] = { fg = colors.fg },
  ["@function"] = { fg = colors.green },
  ["@function.builtin"] = { fg = colors.green },
  ["@method"] = { fg = colors.green },
  ["@field"] = { fg = colors.blue },
  ["@property"] = { fg = colors.blue },
  ["@parameter"] = { fg = colors.purple },
  ["@namespace"] = { fg = colors.blue },
  ["@tag"] = { fg = colors.blue },
  ["@tag.delimiter"] = { fg = colors.fg },
  ["@attribute"] = { fg = colors.purple },
  ["@operator"] = { fg = colors.fg },
  ["@punctuation"] = { fg = colors.fg },
  ["@punctuation.delimiter"] = { fg = colors.fg },
  ["@number"] = { fg = colors.purple },
  ["@boolean"] = { fg = colors.purple },
  ["@class"] = { fg = colors.blue },
  ["@interface"] = { fg = colors.blue },
  ["@struct"] = { fg = colors.blue },
  ["@enum"] = { fg = colors.purple },
  ["@enumMember"] = { fg = colors.purple },

  -- Diff (fugitive, diffsplit, etc.)
  DiffAdd = { bg = "#1e2e1e" },
  DiffDelete = { bg = "#2e1e1e" },
  DiffChange = { bg = "#1e2433" },
  DiffText = { bg = "#2e2030" },
}

vim.cmd("hi clear")
vim.opt.termguicolors = true
vim.g.colors_name = "capo-dark"

for group, attrs in pairs(highlights) do
  vim.api.nvim_set_hl(0, group, attrs)
end